try {
  raise RuntimeError("example");
  assert(false);
} catch e: RuntimeError {
  assertEq(e.message, "example");
}