try {
  raise Error("example");
  assert(false);
} catch _ {
  assert(true);
}