try {
  raise Error("raise");
  assert(false);
} catch e: Error {
  try {
    raise Error("raise");
    assert(false);
  } catch e: Error {
    assert(true);
  }
}